[package]
name = "advent-of-code-rs"
version = "0.1.0"
authors = ["stssrn <stssrn@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
anyhow = "1.0"
log = "0.4"
pretty_env_logger = "0.4"
