[workspace]

members = [
    "day_01a",
    "day_01b",
    "day_02a",
    "day_02b",
    "day_03a",
    "day_03b",
    "day_04a",
    "day_04b",
    "day_05a",
    "day_05b",
    "day_06a",
    "day_06b",
]
